- id: nila
  name: nila
  description: "Nila: a Python formatter forked from Pyink"
  entry: nila
  language: python
  minimum_pre_commit_version: 2.9.2
  require_serial: true
  types_or: [python, pyi]
