- id: indigo
  name: indigo
  description: "Indigo: a Python formatter forked from Pyink"
  entry: indigo
  language: python
  minimum_pre_commit_version: 2.9.2
  require_serial: true
  types_or: [python, pyi]
